#!/bin/bash
source $(dirname $0)/buildqueue.conf

function runQueueItem {
	(
		echo " "
		echo "------------------------------------------------------------"
		echo "running queueitem $(date +%Y%m%d\ %H%M%S)"
		echo "------------------------------------------------------------"
		source ${queuedir}/${1}
		rm -f ${queuedir}/${1}
	) >> ~/log/buildqueue.log 2>&1
}

if [ $(ls -1 ${queuedir} | wc -l) -gt 0 ]
then
	for file in $(ls -1 ${queuedir})
	do
		runQueueItem ${file}
	done
fi

inotifywait -m --format '%f' -e close_write ${queuedir} | while read file
do
	runQueueItem ${file}
done
