#!/bin/bash
source $(dirname $0)/config

if test -e /tmp/buildbot; then
	echo "another buildbot is running, quitting"
else
	[ "$1" = "" ] && exit 1
	touch /tmp/buildbot
	cd ${rpdir}
	git checkout master
	git checkout *
	git pull origin master
	cd ${rpdir}/${1}
	buildrepo
	[ $? -eq 0 ] && syncrepo
	rm -f /tmp/buildbot
fi
