#!/bin/bash
source $(dirname $0)/config

curdir=$(pwd)

folders=$(ls -1 ${curdir})

for folder in ${folders}
do
  if [ -d ${folder} ];
  then
    cd ${folder}
    buildone
    cd ${curdir}
  fi
done

