#!/bin/bash
source $(dirname $0)/buildqueue.conf

function runQueueItem {
	(
		echo " "
		echo "------------------------------------------------------------"
		echo "running queueitem $(date +%Y%m%d\ %H%M%S)"
		echo "------------------------------------------------------------"
		source ${queuedir}/${1}
		rm -f ${queuedir}/${1}
	) >> ~/log/buildqueue.log 2>&1
}

if [ $(ls -1 ${queuedir} | wc -l) -gt 0 ]
then
	for file in $(ls -1 ${queuedir})
	do
		runQueueItem ${file}
	done
fi

inotifywait -q -m --format '%f' ${queuedir} -e create -e move -e modify | while read file
do
	if [ -e ${queuedir}/${file} ]; then
		runQueueItem ${file}
	fi
done
