#!/bin/bash
source $(dirname $0)/config

[ "${1}" = "" ] && ( echo "need at least the location where to build" && exit )

if [ "${2}" != "" ]; then
	buildqueue-add "cd ${rpdir}" "git pull origin master" "buildone '${2}' '${1}'" "git push origin master"
else
	buildqueue-add "cd ${rpdir}" "git pull origin master" "buildone '' '${1}'" "git push origin master"
fi
