#!/bin/bash
source $(dirname $0)/config

source repository

returndir=`pwd`

packtemp=$(ls -1)

[ -e ${dest}/${repository}.txt ] && rm -f ${dest}/${repository}.txt

for package in ${packtemp}
do
	if [ -d ${package} ]
	then
		echo ${package}.* >> ${dest}/${repository}.txt
	fi
done

function cleanRepo() {
[ "$1" = "" ] && return 1
packagesdir=${dest}/${repository/-any/}/${1}
cd ${packagesdir}
ls -1 *.pkg.tar.* | grep -xv "$(cat ${dest}/${repository}.txt)"
rm -f $(ls -1 *.pkg.tar.* | grep -xv "$(cat ${dest}/${repository}.txt)")
}

if [ "${rarch}" = "any" ]; then
	cleanRepo any
else
	for _arch in ${rarch}; do
		cleanRepo ${_arch}
	done
fi

rm -f ${dest}/${repository}.txt

cd ${returndir}

regenrepo clean
