#!/bin/bash
PATH=$PATH:$(cd $(dirname $BASH_SOURCE) && pwd)

# path
rpdir=~/herecura
dest=~/repo

# sources path
sourcesdir=~/sources

# chroot paths
arch32=/home/build/.chroots/arch32
arch64=/home/build/.chroots/arch64

# SyncRepo
SyncRepo=~/bin/SyncRepo
