#!/bin/bash
source $(dirname $0)/config

# goto herecura-stable
cd ${rpdir}/herecura-stable || exit

# make the packages in the correct sequence
(cd gstreamer0.10-be; buildone);
(cd gstreamer0.10-be-base; buildone);
(cd gstreamer0.10-be-good; buildone);
(cd gstreamer0.10-be-bad; buildone);
(cd gstreamer0.10-be-ugly; buildone);
(cd gstreamer0.10-be-ffmpeg; buildone);
(cd gstreamer0.10-be-python; buildone);

