#!/bin/bash
if test -e /tmp/buildbot; then
	echo "buildbot is running, quitting"
  exit
fi

dest=/data/packages/repo
source repository

function regenRepo() {
[ "$1" = "" ] && return 1
packagesdir=${dest}/${repository}/${1}
cd ${packagesdir}
if [ "$2" = "clean" ]
then
  rm -f ${repository}.db.tar.*
fi
repo-add ${repository}.db.tar.gz *.pkg.tar.*
}

if [ "${rarch}" = "any" ]; then
	regenRepo any $1
else
	for _arch in ${rarch}; do
		regenRepo ${_arch} $1
	done
fi
