#!/bin/bash
source $(dirname $0)/config

function month {
case "$1" in
	Jan)
		echo "01"
	;;
	Feb)
		echo "02"
	;;
	Mar)
		echo "03"
	;;
	Apr)
		echo "04"
	;;
	May)
		echo "05"
	;;
	Jun)
		echo "06"
	;;
	Jul)
		echo "07"
	;;
	Aug)
		echo "08"
	;;
	Sep)
		echo "09"
	;;
	Oct)
		echo "10"
	;;
	Nov)
		echo "11"
	;;
	Dec)
		echo "12"
	;;
esac
}

cd ${rpdir}
git pull origin master

mainfolder="${rpdir}/herecura-stable-any"

# adblock main
(
cd ${mainfolder}/opera-adblock-main
filename='urlfilter-main.ini'
rm -f ${filename}
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/urlfilter.ini
if [ $? -eq 0 ]; then
	arrDate=( $(cat ${filename} | grep Updated | sed 's/.*\([0-9]\{2\}\).*\([A-Za-z]\{3\}\).*\([0-9]\{4\}\).*/\3 \2 \1/g') )
	filedate=${arrDate[0]}$(month ${arrDate[1]})${arrDate[2]}
	sed -e "s/pkgver=.*/pkgver=${filedate}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-main
	git commit -sm "opera-adblock-main :: ${filedate}"
fi
)

# adblock stat
(
cd ${mainfolder}/opera-adblock-stat
filename='urlfilter-stat.ini'
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/complete/urlfilter.ini
if [ $? -eq 0 ]; then
	arrDate=( $(cat ${filename} | grep Updated | sed 's/.*\([0-9]\{2\}\).*\([A-Za-z]\{3\}\).*\([0-9]\{4\}\).*/\3 \2 \1/g') )
	filedate=${arrDate[0]}$(month ${arrDate[1]})${arrDate[2]}
	sed -e "s/pkgver=.*/pkgver=${filedate}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-stat
	git commit -sm "opera-adblock-stat :: ${filedate}"
fi
)

# v4 elements css
(
cd ${mainfolder}/opera-adblock-elements
filename='fanboy-adblocklist-elements-v4.css'
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/fanboy-adblocklist-elements-v4.css
if [ $? -eq 0 ]; then
	arrDate=( $(cat ${filename} | grep Updated | sed 's/.*\([0-9]\{2\}\).*\([A-Za-z]\{3\}\).*\([0-9]\{4\}\).*/\3 \2 \1/g') )
	filedate=${arrDate[0]}$(month ${arrDate[1]})${arrDate[2]}
	sed -e "s/pkgver=.*/pkgver=${filedate}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-elements
	git commit -sm "opera-adblock-elements :: ${filedate}"
fi
)

git push origin master

(cd herecura-stable-any/opera-adblock-main; buildone)
(cd herecura-stable-any/opera-adblock-stat; buildone)
(cd herecura-stable-any/opera-adblock-elements; buildone)

syncrepo
