#!/bin/bash
source "$(dirname $0)/../app-init"

cd ${rpdir}

folders=$(ls -1 ${rpdir}/testing)
for folder in ${folders}
do
	msg "try to start build for $folder"
	if [ -d ${rpdir}/${rpfolder}/${folder} ];
	then
		buildone '' ${rpfolder}/${folder}
	fi
done

cd ${rpdir}
git push origin master
git reset --hard
