#!/bin/bash
source "$(dirname $0)/../app-init"

cd ${rpdir}
git pull origin master

mainfolder="${rpdir}/stable"
date=$(date +%Y%m%d)

# adblock main
(
msg "opera-adblock-main"
cd ${mainfolder}/opera-adblock-main
filename='urlfilter-main.ini'
rm -f ${filename}
msg "downloading ..."
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/urlfilter.ini
if [ $? -eq 0 ]; then
	msg "update pkgbuild ..."
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	msg "build ..."
	buildone
else
	git checkout ${filename}
fi
)

# adblock stat
(
msg "opera-adblock-stat"
cd ${mainfolder}/opera-adblock-stat
filename='urlfilter-stat.ini'
msg "downloading ..."
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/complete/urlfilter.ini
if [ $? -eq 0 ]; then
	msg "update pkgbuild ..."
	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${date}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	msg "build ..."
	buildone
else
	git checkout ${filename}
fi
)

# v4 elements css
(
msg "opera-adblock-elements"
cd ${mainfolder}/opera-adblock-elements
filename='fanboy-adblocklist-elements-v4.css'
msg "downloading ..."
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/fanboy-adblocklist-elements-v4.css
if [ $? -eq 0 ]; then
	msg "update pkgbuild ..."
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	msg "build ..."
	buildone
else
	git checkout ${filename}
fi
)

git push origin master
