#!/bin/bash
source "$(dirname $0)/../app-init"

cd ${rpdir}
git pull origin master

appname=pdfminer
msg "autoupdate $appname"

# cd to folder of ${appname}
cd stable/${appname}

source PKGBUILD
msg "$appname version: $pkgver"

# get version from site
msg "get new version of $appname"
nwVersion=$(wget -q -O- http://pypi.python.org/pypi/pdfminer/ | grep -m1 -ie "<a.*pdfminer-[0-9\.]*\.tar\.gz" | sed 's,.*pdfminer-\([0-9\.]*\)\.tar\.gz.*,\1,')
msg "$appname new version: $nwVersion"

if [ $(vercmp "$nwVersion" "$pkgver") -gt 0 ]; then
	msg "$appname :: update PKGBUILD to version $nwVersion"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	mkpres=$?
	rm -rf src
	if [ $mkpres -eq 0 ]; then
		buildqueue-build stable/$appname
	else
		git checkout PKGBUILD
	fi
fi
