#!/bin/bash
source "$(dirname $0)/../app-init"

cd ${rpdir}
git pull origin master

appname=php-mongo
msg "autoupdate $appname"

# cd to folder of ${appname}
cd pre-community/${appname}

source PKGBUILD
msg "$appname version: $pkgver"

# get version from site
msg "get new version of $appname"
nwVersion=$(wget -q -O- http://pecl.php.net/package/mongo | grep -m1 -ie "\/get\/mongo-[0-9\.]*\.tgz" | sed 's,.*<a.*mongo-\([0-9\.]*\)\.tgz.*,\1,')
msg "$appname new version: $nwVersion"

if [ $(vercmp "$nwVersion" "$pkgver") -gt 0 ]; then
	msg "$appname :: update PKGBUILD to version $nwVersion"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	mkpres=$?
	rm -rf src
	if [ $mkpres -eq 0 ]; then
		buildqueue-build pre-community/$appname
	else
		git checkout PKGBUILD
	fi
fi
