#!/bin/bash
source "$(dirname $0)/../app-init"

cd ${rpdir}
git pull origin master

appname=python2-gflags
msg "autoupdate $appname"

# cd to folder of ${appname}
cd pre-community/${appname}

source PKGBUILD
msg "$appname version: $pkgver"

# get version from site
nwVersion=$(wget -q -O- http://code.google.com/p/python-gflags/downloads/list | grep -m1 -ie "<a.*python-gflags-[0-9\.]*\.tar\.gz.*Download" | sed 's,.*python-gflags-\([0-9\.]*\)\.tar\.gz.*,\1,')
msg "$appname new version: $nwVersion"

if [ $(vercmp "$nwVersion" "$pkgver") -gt 0 ]; then
	msg "$appname :: update PKGBUILD to version $nwVersion"

	#cat PKGBUILD |\
	#sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		#-e "s/^pkgrel=.*/pkgrel=1/g" |\
	#awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	#> PKGBUILD-updated
	#mv PKGBUILD-updated PKGBUILD
	#makepkg -g >> PKGBUILD
	#mkpres=$?
	#if [ $mkpres -eq 0 ]; then
		#buildqueue-build pre-community/$appname
	#else
		#git checkout PKGBUILD
	#fi
fi
