#!/bin/bash
source "$(dirname $0)/../app-init"

cd ${rpdir}
git pull origin master

appname=vim
msg "autoupdate $appname"

# cd to folder of ${appname}
cd stable/${appname}

source PKGBUILD
msg "$appname version: $pkgver"

# get version from site
msg "get new version of $appname"
nwVersion=$(wget -q -O- https://code.google.com/p/vim/source/list | grep -m1 -ie "<a.*Added tag.*for changeset.*" | sed -e 's,.*Added tag v\([0-9a-d-]*\).*,\1,' -e 's,-,.,g')
baseVersion=$(echo $nwVersion | sed -e 's/\([0-9]*\.[0-9a-d]*\)\.\([0-9]*\)/\1/')
patchLevel=$(echo $nwVersion | sed -e 's/\([0-9]*\.[0-9a-d]*\)\.\([0-9]*\)/\2/')
msg "$appname new version: $nwVersion"

if [ $(vercmp "$nwVersion" "$pkgver") -gt 0 ]; then
	msg "$appname :: update PKGBUILD to version $nwVersion"

	cat PKGBUILD |\
	sed -e "s/^_basever=.*/_basever=${baseVersion}/g" \
		-e "s/^_patchlevel=.*/_patchlevel=${patchLevel}/g" \
		-e 's/^__hgrev=.*/__hgrev=v${pkgver\/\/.\/-}/g' \
		-e "s/^pkgrel=.*/pkgrel=1/g" \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	mkpres=$?
	if [ $mkpres -eq 0 ]; then
		buildqueue-build stable/$appname
	else
		git checkout PKGBUILD
	fi
fi
