#!/bin/bash
source $(dirname $0)/../config-archlinux

appname=closure-compiler

(
cd "$rpdir"
communityco "$appname"
cd "$appname/trunk"

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://code.google.com/p/closure-compiler/downloads/list | grep -m1 -ie "<a.*compiler-[0-9\.]*\.tar\.gz.*Download" | sed 's,.*compiler-\([0-9\.]*\)\.tar\.gz.*,\1,')

if [ $(vercmp "$nwVersion" "$pkgver") -gt 0 ]; then
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	mkpres=$?
	if [ $mkpres -eq 0 ]; then
		buildone-archlinux
		if [ $? -ne 0 ]; then
			svn revert PKGBUILD
		fi
	else
		svn revert PKGBUILD
	fi
fi
)
