#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=closure-compiler

(
# cd to folder of ${appname}
cd stable-any/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://code.google.com/p/closure-compiler/downloads/list | grep -m1 -ie "<a.*compiler-[0-9\.]*\.tar\.gz.*Download" | sed 's,.*compiler-\([0-9\.]*\)\.tar\.gz.*,\1,')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "${appname} :: is already on the latest version"
else
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	mkpres=$?
	rm -rf src 
	if [ $mkpres -eq 0 ]; then
		buildone
	else
		git checkout PKGBUILD
	fi
fi
)
