#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

(
# cd to folder of colibri
cd herecura-stable/colibri

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://kde-apps.org/content/show.php/Colibri?content=117147 | grep -ie 'contentmainheadline.*colibri' | sed 's/.*<span class=\"contentdata\">\([0-9\.]*\)<\/span>.*/\1/g')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "colibri :: is already on the latest version"
else
	echo "colibri :: update PKGBUILD to version ${nwVersion}"
	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src 
	git add .
	git commit -sm "colibri :: ${nwVersion}"
	git push origin master
	buildone
fi
)
