#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=$1
content=$2
searchfor="$3"

(
# cd to folder of ${appname}
cd herecura-stable/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://kde-apps.org/content/show.php?content=${content} | grep -ie "<h1.*contentmainheadline.*${searchfor}</h1>" | sed 's/.*<span class=\"contentdata\">\([0-9\.a-z]*\)<\/span>.*/\1/g')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "${appname} :: is already on the latest version"
else
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src 
	buildone
	if [ $? -eq 0 ]; then
		git add .
		git commit -sm "${appname} :: ${nwVersion}"
		git push origin master
	else
		git checkout PKGBUILD
	fi
fi
)
