#!/bin/bash
source $(dirname $0)/../config

buildqueue-add \
	"~/archbuild/update/closure-compiler" \
	"~/archbuild/update/closure-linter" \
	"~/archbuild/update/colibri" \
	"~/archbuild/update/httrack" \
	"~/archbuild/update/jalbum" \
	"~/archbuild/update/kcm-grub2" \
	"~/archbuild/update/kcm-qt-graphicssystem" \
	"~/archbuild/update/kcm-wacomtablet" \
	"~/archbuild/update/kmtail" \
	"~/archbuild/update/kpartsplugin" \
	"~/archbuild/update/kpassgen" \
	"~/archbuild/update/kps" \
	"~/archbuild/update/kwooty" \
	"~/archbuild/update/lcdproc" \
	"~/archbuild/update/lirc-bede" \
	"~/archbuild/update/mkclean" \
	"~/archbuild/update/mkvtoolnix-be" \
	"~/archbuild/update/nmapsi4" \
	"~/archbuild/update/nntpgrab" \
	"~/archbuild/update/opera" \
	"~/archbuild/update/php-mongo" \
	"~/archbuild/update/python2-gflags" \
	"~/archbuild/update/python2-pymongo" \
	"~/archbuild/update/python2-yenc" \
	"~/archbuild/update/xmlindent" \
	"~/archbuild/update/xmlstarlet"
