#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}

for rpfolder in 'herecura-testing-any' 'herecura-testing'
do
	folders=$(ls -1 ${rpdir}/${rpfolder})
	for folder in ${folders}
	do
		if [ -d ${rpdir}/${rpfolder}/${folder} ];
		then
			buildone ${rpfolder}/${folder}
			if [ $? -eq 0 ]; then
				source ${rpdir}/${rpfolder}/${folder}/PKGBUILD
				git add ${rpdir}/${rpfolder}/${folder}
				git commit -sm "${pkgname} :: ${pkgver}"
			else
				git checkout ${rpdir}/${rpfolder}/${folder}/PKGBUILD
			fi
		fi
	done
done

cd ${rpdir}
git push origin master

