#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=jalbum

(
# cd to folder of ${appname}
cd herecura-stable-any/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://jalbum.net/en/software/download | grep -ie "<h1 class=\"addpad20\"" | sed 's,.*<h1.*>[A-Za-z\ ]*\([0-9\.]*\).*</h1>.*,\1,g')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "${appname} :: is already on the latest version"
else
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src 
	buildone
	if [ $? -eq 0 ]; then
		git add .
		git commit -sm "${appname} :: ${nwVersion}"
		git push origin master
	else
		git checkout PKGBUILD
	fi
fi
)
