#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=lirc-bede

(
# cd to folder of ${appname}
cd stable/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://sourceforge.net/projects/lirc/ | grep -m1 -ie "<a\ href=.*\/lirc.*tar\.bz2" | sed 's,.*<a href=".*title=.*lirc-\(.*\)\.tar\.bz2.*,\1,')

if [ $(vercmp "$nwVersion" "$pkgver") -gt 0 ]; then
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	mkpres=$?
	rm -rf src
	if [ $mkpres -eq 0 ]; then
		buildone
	else
		git checkout PKGBUILD
	fi
fi
)
