#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=nntpgrab

(
# cd to folder of ${appname}
cd stable/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://www.nntpgrab.nl/projects/nntpgrab/wiki/Downloads | grep -ie "source code can be found at" | sed 's,.*<a.*nntpgrab-\([0-9\.]*\)\.tar\.bz2.*,\1,')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "${appname} :: is already on the latest version"
else
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	mkpres=$?
	rm -rf src
	if [ $mkpres -eq 0 ]; then
		buildone
	else
		git checkout PKGBUILD
	fi
fi
)
