#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

mainfolder="${rpdir}/herecura-stable-any"
date=$(date +%Y%m%d)

# adblock main
(
cd ${mainfolder}/opera-adblock-main
filename='urlfilter-main.ini'
rm -f ${filename}
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/urlfilter.ini
if [ $? -eq 0 ]; then
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	buildone
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-main
	git commit -sm "opera-adblock-main :: ${date}"
fi
)

# adblock stat
(
cd ${mainfolder}/opera-adblock-stat
filename='urlfilter-stat.ini'
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/complete/urlfilter.ini
if [ $? -eq 0 ]; then
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	buildone
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-stat
	git commit -sm "opera-adblock-stat :: ${date}"
fi
)

# v4 elements css
(
cd ${mainfolder}/opera-adblock-elements
filename='fanboy-adblocklist-elements-v4.css'
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/fanboy-adblocklist-elements-v4.css
if [ $? -eq 0 ]; then
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	buildone
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-elements
	git commit -sm "opera-adblock-elements :: ${date}"
fi
)

git push origin master
