#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
cd testing/opera-next
wget -O PKGBUILD http://snapshot.opera.com/unix/latest/.unsupported/PKGBUILD
if [ $? -eq 0 ]; then
	sed -e 's/#_opdistro/_opdistro/' -i PKGBUILD
	git diff --no-ext-diff --quiet --exit-code PKGBUILD
	if [ $? -ne 0 ]; then
		cd ${rpdir}
		buildone '' testing/opera-next
	fi
else
	git checkout ${filename}
fi
