#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

mainfolder="${rpdir}/herecura-stable-any"
date=$(date +%Y%m%d)

BUILD_ADBLOCK_MAIN=0
BUILD_ADBLOCK_STAT=0
BUILD_ADBLOCK_CSS=0

# adblock main
(
cd ${mainfolder}/opera-adblock-main
filename='urlfilter-main.ini'
rm -f ${filename}
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/urlfilter.ini
if [ $? -eq 0 ]; then
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-main
	git commit -sm "opera-adblock-main :: ${date}"
	BUILD_ADBLOCK_MAIN=1
fi
)

# adblock stat
(
cd ${mainfolder}/opera-adblock-stat
filename='urlfilter-stat.ini'
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/complete/urlfilter.ini
if [ $? -eq 0 ]; then
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-stat
	git commit -sm "opera-adblock-stat :: ${date}"
	BUILD_ADBLOCK_STAT=1
fi
)

# v4 elements css
(
cd ${mainfolder}/opera-adblock-elements
filename='fanboy-adblocklist-elements-v4.css'
wget -q -O ${filename} http://www.fanboy.co.nz/adblock/opera/fanboy-adblocklist-elements-v4.css
if [ $? -eq 0 ]; then
	sed -e "s/pkgver=.*/pkgver=${date}/g" \
		-e "/.*sums.*/d" \
		-i PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src
	cd ${rpdir}
	git add herecura-stable-any/opera-adblock-elements
	git commit -sm "opera-adblock-elements :: ${date}"
	BUILD_ADBLOCK_CSS=1
fi
)

git push origin master

if [ $BUILD_ADBLOCK_MAIN -ne 0 ]; then
	buildone herecura-stable-any/opera-adblock-main/
fi
if [ $BUILD_ADBLOCK_STAT -ne 0 ]; then
	buildone herecura-stable-any/opera-adblock-stat/
fi
if [ $BUILD_ADBLOCK_CSS -ne 0 ]; then
	buildone herecura-stable-any/opera-adblock-elements/
fi
