#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=python2-pymongo

(
# cd to folder of ${appname}
cd stable/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://pypi.python.org/pypi/pymongo/ | grep -m1 -ie "<a.*pymongo-[0-9\.]*\.tar\.gz" | sed 's,.*pymongo-\([0-9\.]*\)\.tar\.gz.*,\1,')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "${appname} :: is already on the latest version"
else
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src 
	buildone
fi
)
