#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=sabnzbd

(
# cd to folder of ${appname}
cd stable-any/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://sabnzbd.org/download/ | grep -ie "current stable" | sed 's,.*Version: \([0-9\.]*\).*,\1,i')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "${appname} :: is already on the latest version"
else
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src 
	buildone
fi
)
