#!/bin/bash
source $(dirname $0)/../config

cd ${rpdir}
git pull origin master

appname=xmlindent

(
# cd to folder of ${appname}
cd stable/${appname}

source PKGBUILD

# get version from site
nwVersion=$(wget -q -O- http://sourceforge.net/projects/xmlindent/ | grep -ie "<a\ href=.*\/xmlindent.*tar\.gz"  | sed 's,.*<a href=".*title=.*xmlindent-\(.*\)\.tar\.gz.*,\1,')

if [ "${nwVersion}" = "${pkgver}" ]; then
	echo "${appname} :: is already on the latest version"
else
	echo "${appname} :: update PKGBUILD to version ${nwVersion}"

	cat PKGBUILD |\
	sed -e "s/^pkgver=.*/pkgver=${nwVersion}/g"  \
		-e "s/^pkgrel=.*/pkgrel=1/g" |\
	awk '/^.*sums=\(/,/)/ { next } 1 {print $0 }' \
	> PKGBUILD-updated
	mv PKGBUILD-updated PKGBUILD
	makepkg -g >> PKGBUILD
	rm -rf src 
	buildone
fi
)
